export const SET_SELECTED_GRAVITY = 'SET_SELECTED_GRAVITY'
export const SET_CROP_X_OFFSET = 'SET_CROP_X_OFFSET'
export const SET_CROP_Y_OFFSET = 'SET_CROP_Y_OFFSET'
export const SET_CROP_OFFSET_TYPE = 'SET_CROP_OFFSET_TYPE'
